easy.n=15
easy.m=15
easy.foodAmount=2
easy.wallAmount=0
easy.targetLength=10
easy.tickMs=400

medium.n=20
medium.m=20
medium.foodAmount=2
medium.wallAmount=15
medium.targetLength=15
medium.tickMs=250

hard.n=50
hard.m=50
hard.foodAmount=3
hard.wallAmount=40
hard.targetLength=20
hard.tickMs=130

window.width=600
window.height=600
min.cell.size=8